import { Store } from './store';
import { CompanyContact } from './company-contact';
import { Request } from './request';
import {Staff} from "src/app/models/staff";

export class Company {
    company_id: number;
    parent_company_id: number;
    company_name: string;
    company_common_name_en: string;
    company_created_at: string;
    company_status_override: string;
    company_updated_at: string;
    is_request_updates_in_30_days: string;
    no_of_active_requests: string;
    total_candidate: string;
    company_common_name_ar: string;
    company_description_en: string;
    company_description_ar: string;
    company_website: string;
    company_email: string;
    company_logo: string;
    company_status: number;
    total_candidates: number;
    total_suggestions: number;
    total_stores: number;
    total_subcompanies: number;
    company_hourly_rate: number;
    company_bonus_commission: number;
    company_followup: any;
    company_followup_interval_weeks: any;
    company_last_followup_datetime: any;
    currency_pref: number;
    transferInLast40Days: number;
    company_approved_to_hire: any;
    password: any;
    staff_id: any;
    subcompanies: Company[];
    subCompanies: Company[];
    stores: Store[];
    files: any[];
    brands: any[];
    notes: any[];
    staff: Staff;
    companyContacts: CompanyContact[];
    requests: Request[];
    parentTransfers: any[];
}
